name: Bug
description: File a bug/issue
title: "[BUG] <title>"
#labels: ["bug"]
#type: bug
body:
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: |
      Please search to see if an issue already exists for the bug you encountered.
      If the issue is for a plugin (except for mimeTools, NppConverter, and NppExport),
      report it to the plugin author rather than here.
    options:
    - label: I have searched the existing issues
      required: true
- type: checkboxes
  attributes:
    label: Is the issue reproducible in PaperWasp without plugins?
    description: |
      If feasible, try launching PaperWasp without any plugins.
      Some updates to PaperWasp modify communication rules used by plugins,
      and if plugin developers do not keep their plugins in sync with these changes, issues may arise.
      Running without plugins can help diagnose specific problems.
      You can temporarily move your user plugin folder, usually `~/Library/Application Support/PaperWasp/plugins`.
    options:
    - label: I have tried PaperWasp without plugins
      required: false
- type: checkboxes
  attributes:
    label: Is the issue reproducible with a clean PaperWasp configuration?
    description: |
      If feasible, try launching PaperWasp with a clean user configuration.
      It can help diagnose whether a specific configuration is causing the issue.
    options:
    - label: I have tried a clean PaperWasp configuration
      required: false
- type: checkboxes
  attributes:
    label: Does the issue affect SciTE?
    description: |
      PaperWasp relies on the Lexilla and Scintilla libraries.
      For more details, visit https://github.com/ScintillaOrg/lexilla and https://sourceforge.net/p/scintilla.
      Consider using the reference program SciTE to verify whether the issue is in the shared editor/lexer stack.
      Download Scite from here https://www.scintilla.org/SciTEDownload.html.
    options:
    - label: I have tried SciTE
      required: false
- type: textarea
  attributes:
    label: Description of the Issue
    description: Provide a concise description to the issue itself.
  validations:
    required: true
- type: textarea
  attributes:
    label: Steps To Reproduce
    description: Steps to reproduce the behavior.
    placeholder: |
      1.  
      2.  
      3.  
      ...
    value: |
      1.  
      2.  
      3.  
  validations:
    required: true
- type: textarea
  attributes:
    label: Current Behavior
    description: What you're experiencing.
  validations:
    required: true
- type: textarea
  attributes:
    label: Expected Behavior
    description: What did you expect to happen.
  validations:
    required: true
- type: textarea
  attributes:
    label: Debug Information
    description: |
      In PaperWasp, click on the "?" menu (found to the right of "Window" in the menu bar).
      In the menu that drops down, choose "Debug Info...".
      A dialog will open detailing specifics about your PaperWasp version, plugins, etc.
      CLICK ON THE BUTTON "Copy debug info into clipboard".
      Do a PASTE HERE
    render: shell
  validations:
    required: true
- type: textarea
  attributes:
    label: Anything else?
    description: |
      Links? References? Anything that will give us more context about the issue you are encountering!

      Tip: You can attach images or relevant text files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
